

using ExceptionPractice;

internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
        PracticeClass.innerExceptionTest();
    }
}